# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('iscomplete', models.CharField(max_length=200)),
            ],
        ),
    ]
