# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='iscomplete',
            field=models.BooleanField(),
        ),
    ]
