# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161026_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='iscomplete',
            new_name='isComplete',
        ),
    ]
